# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/v1/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/v1/common.proto',
  package='common.v1',
  syntax='proto3',
  serialized_options=b'Z9github.modzy.engineering/platform/protos/gen/go/common/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63ommon/v1/common.proto\x12\tcommon.v1\x1a\x1fgoogle/api/field_behavior.proto\"I\n\x0fModelIdentifier\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x11\n\x04name\x18\x03 \x01(\tB\x03\xe0\x41\x03\"|\n\x0cModelLibrary\x12\x12\n\nidentifier\x18\x05 \x01(\t\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x63\x61_certificate\x18\x03 \x01(\t\x12%\n\x08registry\x18\x04 \x01(\x0b\x32\x13.common.v1.Registry\"\x7f\n\x16ModelAutoscalingConfig\x12)\n\x05model\x18\x01 \x01(\x0b\x32\x1a.common.v1.ModelIdentifier\x12\x0f\n\x07minimum\x18\x02 \x01(\r\x12\x0f\n\x07maximum\x18\x03 \x01(\r\x12\x18\n\x10model_library_id\x18\x04 \x01(\t\"T\n\x08Registry\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x13\n\x0b\x63redentials\x18\x03 \x01(\t\x12\x17\n\x0fskip_tls_verify\x18\x05 \x01(\x08\"\xf5\x01\n\x0bListOptions\x12\x34\n\x07\x66ilters\x18\x01 \x03(\x0b\x32#.common.v1.ListOptions.FiltersEntry\x12.\n\x04sort\x18\x02 \x03(\x0b\x32 .common.v1.ListOptions.SortEntry\x12#\n\x04page\x18\x03 \x01(\x0b\x32\x15.common.v1.Pagination\x1a.\n\x0c\x46iltersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\tSortEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"*\n\nPagination\x12\x0e\n\x06number\x18\x01 \x01(\r\x12\x0c\n\x04size\x18\x02 \x01(\rB;Z9github.modzy.engineering/platform/protos/gen/go/common/v1b\x06proto3'
  ,
  dependencies=[google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,])




_MODELIDENTIFIER = _descriptor.Descriptor(
  name='ModelIdentifier',
  full_name='common.v1.ModelIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='common.v1.ModelIdentifier.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='common.v1.ModelIdentifier.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='common.v1.ModelIdentifier.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=143,
)


_MODELLIBRARY = _descriptor.Descriptor(
  name='ModelLibrary',
  full_name='common.v1.ModelLibrary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='common.v1.ModelLibrary.identifier', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='common.v1.ModelLibrary.url', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='common.v1.ModelLibrary.name', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ca_certificate', full_name='common.v1.ModelLibrary.ca_certificate', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='registry', full_name='common.v1.ModelLibrary.registry', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=269,
)


_MODELAUTOSCALINGCONFIG = _descriptor.Descriptor(
  name='ModelAutoscalingConfig',
  full_name='common.v1.ModelAutoscalingConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='common.v1.ModelAutoscalingConfig.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minimum', full_name='common.v1.ModelAutoscalingConfig.minimum', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maximum', full_name='common.v1.ModelAutoscalingConfig.maximum', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_library_id', full_name='common.v1.ModelAutoscalingConfig.model_library_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=398,
)


_REGISTRY = _descriptor.Descriptor(
  name='Registry',
  full_name='common.v1.Registry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='common.v1.Registry.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='common.v1.Registry.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='credentials', full_name='common.v1.Registry.credentials', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skip_tls_verify', full_name='common.v1.Registry.skip_tls_verify', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=484,
)


_LISTOPTIONS_FILTERSENTRY = _descriptor.Descriptor(
  name='FiltersEntry',
  full_name='common.v1.ListOptions.FiltersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='common.v1.ListOptions.FiltersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.v1.ListOptions.FiltersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=687,
)

_LISTOPTIONS_SORTENTRY = _descriptor.Descriptor(
  name='SortEntry',
  full_name='common.v1.ListOptions.SortEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='common.v1.ListOptions.SortEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.v1.ListOptions.SortEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=689,
  serialized_end=732,
)

_LISTOPTIONS = _descriptor.Descriptor(
  name='ListOptions',
  full_name='common.v1.ListOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filters', full_name='common.v1.ListOptions.filters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sort', full_name='common.v1.ListOptions.sort', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='common.v1.ListOptions.page', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LISTOPTIONS_FILTERSENTRY, _LISTOPTIONS_SORTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=732,
)


_PAGINATION = _descriptor.Descriptor(
  name='Pagination',
  full_name='common.v1.Pagination',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='common.v1.Pagination.number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='common.v1.Pagination.size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=734,
  serialized_end=776,
)

_MODELLIBRARY.fields_by_name['registry'].message_type = _REGISTRY
_MODELAUTOSCALINGCONFIG.fields_by_name['model'].message_type = _MODELIDENTIFIER
_LISTOPTIONS_FILTERSENTRY.containing_type = _LISTOPTIONS
_LISTOPTIONS_SORTENTRY.containing_type = _LISTOPTIONS
_LISTOPTIONS.fields_by_name['filters'].message_type = _LISTOPTIONS_FILTERSENTRY
_LISTOPTIONS.fields_by_name['sort'].message_type = _LISTOPTIONS_SORTENTRY
_LISTOPTIONS.fields_by_name['page'].message_type = _PAGINATION
DESCRIPTOR.message_types_by_name['ModelIdentifier'] = _MODELIDENTIFIER
DESCRIPTOR.message_types_by_name['ModelLibrary'] = _MODELLIBRARY
DESCRIPTOR.message_types_by_name['ModelAutoscalingConfig'] = _MODELAUTOSCALINGCONFIG
DESCRIPTOR.message_types_by_name['Registry'] = _REGISTRY
DESCRIPTOR.message_types_by_name['ListOptions'] = _LISTOPTIONS
DESCRIPTOR.message_types_by_name['Pagination'] = _PAGINATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelIdentifier = _reflection.GeneratedProtocolMessageType('ModelIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _MODELIDENTIFIER,
  '__module__' : 'common.v1.common_pb2'
  # @@protoc_insertion_point(class_scope:common.v1.ModelIdentifier)
  })
_sym_db.RegisterMessage(ModelIdentifier)

ModelLibrary = _reflection.GeneratedProtocolMessageType('ModelLibrary', (_message.Message,), {
  'DESCRIPTOR' : _MODELLIBRARY,
  '__module__' : 'common.v1.common_pb2'
  # @@protoc_insertion_point(class_scope:common.v1.ModelLibrary)
  })
_sym_db.RegisterMessage(ModelLibrary)

ModelAutoscalingConfig = _reflection.GeneratedProtocolMessageType('ModelAutoscalingConfig', (_message.Message,), {
  'DESCRIPTOR' : _MODELAUTOSCALINGCONFIG,
  '__module__' : 'common.v1.common_pb2'
  # @@protoc_insertion_point(class_scope:common.v1.ModelAutoscalingConfig)
  })
_sym_db.RegisterMessage(ModelAutoscalingConfig)

Registry = _reflection.GeneratedProtocolMessageType('Registry', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRY,
  '__module__' : 'common.v1.common_pb2'
  # @@protoc_insertion_point(class_scope:common.v1.Registry)
  })
_sym_db.RegisterMessage(Registry)

ListOptions = _reflection.GeneratedProtocolMessageType('ListOptions', (_message.Message,), {

  'FiltersEntry' : _reflection.GeneratedProtocolMessageType('FiltersEntry', (_message.Message,), {
    'DESCRIPTOR' : _LISTOPTIONS_FILTERSENTRY,
    '__module__' : 'common.v1.common_pb2'
    # @@protoc_insertion_point(class_scope:common.v1.ListOptions.FiltersEntry)
    })
  ,

  'SortEntry' : _reflection.GeneratedProtocolMessageType('SortEntry', (_message.Message,), {
    'DESCRIPTOR' : _LISTOPTIONS_SORTENTRY,
    '__module__' : 'common.v1.common_pb2'
    # @@protoc_insertion_point(class_scope:common.v1.ListOptions.SortEntry)
    })
  ,
  'DESCRIPTOR' : _LISTOPTIONS,
  '__module__' : 'common.v1.common_pb2'
  # @@protoc_insertion_point(class_scope:common.v1.ListOptions)
  })
_sym_db.RegisterMessage(ListOptions)
_sym_db.RegisterMessage(ListOptions.FiltersEntry)
_sym_db.RegisterMessage(ListOptions.SortEntry)

Pagination = _reflection.GeneratedProtocolMessageType('Pagination', (_message.Message,), {
  'DESCRIPTOR' : _PAGINATION,
  '__module__' : 'common.v1.common_pb2'
  # @@protoc_insertion_point(class_scope:common.v1.Pagination)
  })
_sym_db.RegisterMessage(Pagination)


DESCRIPTOR._options = None
_MODELIDENTIFIER.fields_by_name['name']._options = None
_LISTOPTIONS_FILTERSENTRY._options = None
_LISTOPTIONS_SORTENTRY._options = None
# @@protoc_insertion_point(module_scope)
