# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/modzy/common/v1/errors.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#protos/modzy/common/v1/errors.proto\x12\tcommon.v1\"\x84\x01\n\x05\x45rror\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12(\n\x10report_error_url\x18\x02 \x01(\tR\x0ereportErrorUrl\x12\x16\n\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n\x0bstatus_code\x18\x04 \x01(\rR\nstatusCodeBa\n#com.modzy.platform.protos.common.v1P\x01Z8github.modzy.engineering/platform/protos/modzy/common/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.modzy.common.v1.errors_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#com.modzy.platform.protos.common.v1P\001Z8github.modzy.engineering/platform/protos/modzy/common/v1'
  _ERROR._serialized_start=51
  _ERROR._serialized_end=183
# @@protoc_insertion_point(module_scope)
