:doctype: article
:icons: font
:source-highlighter: highlightjs
:docname: Javascript SDK





++++

<div align="center">

<h1>Contributing to Modzy's Python SDK</h1>

<br>
<br>
<br>
<br>



<img alt="GitHub contributors" src="https://img.shields.io/github/contributors/modzy/sdk-python">

<img alt="GitHub last commit" src="https://img.shields.io/github/last-commit/modzy/sdk-python">

<img alt="GitHub Release Date" src="https://img.shields.io/github/issues-raw/modzy/sdk-python">

<br>
<br>

<a href="/CODE_OF_CONDUCT.md" style="text-decoration:none">
    <img src="https://img.shields.io/badge/Contributor%20Covenant-v2.0%20adopted-ff69b4.svg" alt="Contributor Covenant" style="max-width:100%;">
</a>


</div>

<br>
<br>

<div align="center">
<a href="/README.md" style="text-decoration:none">Readme</a> |
<a href="https://docs.modzy.com/docs" style="text-decoration:none">Documentation</a>

</div>

<br>
<br>
<br>
<br>

++++

Contributions are welcome and they are greatly appreciated! Every little bit helps, and credit will always be given.

Below you'll find our contributing requirements, a step-by-step guideline, and our features roadmap.


== Requirements

- Search previous link:https://github.com/modzy/sdk-python/issues[issues] before making new ones to avoid duplicates.
- If you are reporting a bug, please include:
  . Your operating system name and version.
  . Any details about your local setup that might be helpful in troubleshooting.
  . Detailed steps to reproduce the bug.
- If you are proposing a feature:
  . Explain in detail how it would work.
  . Keep the scope as narrow as possible, to make it easier to implement.
  . Remember that this is a volunteer-driven project, and that contributions are welcome.
- File an issue to let us know what you're working on.
- Fork the repo, develop and test your code changes, and add supporting documentation.
- Use descriptive comments throughout your code.
- Add test cases and comment them.
//- Check your spelling and grammar.
- Use descriptive commit messages that clearly explain the changes. Reference the original issue in the pull request.
- Make an individual pull request for each issue.



== Guidelines


=== 1. Fork the repo and set it for local development

Clone the repository:

- `$ git clone https://github.com/modzy/sdk-python.git`

Setup a virtual environment from the local git directory:

- `$ conda create --name modzy-sdk --file .\requirements_dev.txt -c conda-forge`
or for non-conda python distros
- '$ python3 -m venv /path/to/new/virtual/environment'

Activate the virtual environment:

- `$ conda  activate virtual-environ-name`

or for non-conda python distros there are different commands for Linux vs. Windows.

On Linux use source to activate

- `$ source activate virtual-environ-name`

On Windows run the activate.bat file

- `C:>\path\to\virtual\environment\Scripts\activate.bat`


Install dependencies (if not using conda):

- `$ pip3 install -r requirements_dev.txt`


Create a branch for your awesome new feature:

- `$ git checkout -b my-awesome-new-feature`


=== 2. Develop your changes

Fix that bug or build your feature.

=== 3. Run unit tests

Configure the environment variables to easily run all the tests with a single configuration point. 
Note that the environment variables must be set before opening the terminal or program that you will be running your tests from. Environmental variables do not update on the fly.

You can:

==== Set environment variables in bash
There are 2 environmental variables that the test scripts will need.
MODZY_BASE_URL: This variable holds the network address of the modzy installation. Notice the '/api' appeanded to the end of the url. This is mandatory and will cause errors if not present.
MODZY_API_KEY: This variable holds a full copy of a modzy API key. Modzy's role based access controls will cause some of the tests to fail if your key doesn't have all the roles assigned.
===== Windows

[source,bash]
----
set MODZY_BASE_URL=https://modzy.example.com/api
set MODZY_API_KEY=<your Modzy API key here>
----

===== Unix

[source,bash]
----
export MODZY_BASE_URL=https://modzy.example.com/api
export MODZY_API_KEY=<your Modzy API key here>
----

==== Use `.env` file

Create a `.env` file in the root folder with your API key:

[source,python]
----
MODZY_BASE_URL=https://modzy.example.com/api
MODZY_API_KEY=<your Modzy API key here>
----

Run tests:

- `$ py.test`

Or specify the test that you want to run:

- `$ py.test tests.test_client`

=== 4. Document your changes

Add supporting documentation for your code.

//what else would be useful for maintainers?

=== 5. Send a pull request

Add and commit your changes:

- `git add .`

- `$ git commit "A descriptive message"`

Push your branch to GitHub:

- `$ git push origin my-new-awesome-feature`

Initiate a Pull Request: 

If your PR doesn't pass all tests due to role based access controls with your key, please provide log information so that we may test the PR under appropriate conditions.




//== Code of conduct



== Roadmap

- Documentation improvement.
- Comprehensive unit tests.
- Wider API coverage (custom models, accounting, audit, etc).
- [Maybe] Add retry logic for possibly transient issues.
- [Maybe] Consider moving to concrete classes for the API JSON - objects, or else move the ApiObject to a public module.
- [Maybe] Python 2.7 compatibility.




== Support

Use GitHub to report bugs and send feature requests. +
Reach out to https://www.modzy.com/support/ for support requests.
