# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/modzy/accounting/v1/accounting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+protos/modzy/accounting/v1/accounting.proto\x12\raccounting.v1\x1a\x1fgoogle/api/field_behavior.proto\"/\n\x10\x41PIKeyIdentifier\x12\x1b\n\x06prefix\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x06prefix\"8\n\x11\x41\x63\x63ountIdentifier\x12#\n\nidentifier\x18\x01 \x01(\tB\x03\xe0\x41\x02R\nidentifier\"5\n\x0eTeamIdentifier\x12#\n\nidentifier\x18\x01 \x01(\tB\x03\xe0\x41\x02R\nidentifier\"_\n\x0eUserIdentifier\x12\x1e\n\nidentifier\x18\x01 \x01(\tR\nidentifier\x12\x14\n\x05\x65mail\x18\x02 \x01(\tR\x05\x65mail\x12\x17\n\x04name\x18\x03 \x01(\tB\x03\xe0\x41\x03R\x04nameBi\n\'com.modzy.platform.protos.accounting.v1P\x01Z<github.modzy.engineering/platform/protos/modzy/accounting/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.modzy.accounting.v1.accounting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.modzy.platform.protos.accounting.v1P\001Z<github.modzy.engineering/platform/protos/modzy/accounting/v1'
  _APIKEYIDENTIFIER.fields_by_name['prefix']._options = None
  _APIKEYIDENTIFIER.fields_by_name['prefix']._serialized_options = b'\340A\002'
  _ACCOUNTIDENTIFIER.fields_by_name['identifier']._options = None
  _ACCOUNTIDENTIFIER.fields_by_name['identifier']._serialized_options = b'\340A\002'
  _TEAMIDENTIFIER.fields_by_name['identifier']._options = None
  _TEAMIDENTIFIER.fields_by_name['identifier']._serialized_options = b'\340A\002'
  _USERIDENTIFIER.fields_by_name['name']._options = None
  _USERIDENTIFIER.fields_by_name['name']._serialized_options = b'\340A\003'
  _APIKEYIDENTIFIER._serialized_start=95
  _APIKEYIDENTIFIER._serialized_end=142
  _ACCOUNTIDENTIFIER._serialized_start=144
  _ACCOUNTIDENTIFIER._serialized_end=200
  _TEAMIDENTIFIER._serialized_start=202
  _TEAMIDENTIFIER._serialized_end=255
  _USERIDENTIFIER._serialized_start=257
  _USERIDENTIFIER._serialized_end=352
# @@protoc_insertion_point(module_scope)
